### ISSUE TITLE
import enum module error

### ISSUE THREAD

**Issue by Panda-Luffy** [leixingyu/auto-rigger#1]
# Error: ImportError: file C:/Users/xxx/Documents/maya/2020/scripts\autoRigger\constant.py line 3: No module named enum #

**Comment by leixingyu** [comment]
Hi there, can you try installing the backported [enum](https://pypi.org/project/enum34/) package using: `pip install enum34`

Let me know how it goes, and I'll update this in the README, thanks for pointing it out

**Comment by Panda-Luffy** [comment]
OK， I'm try!  thanks!

Xingyu Lei ***@***.***> 于2022年1月16日周日 05:57写道：
